front:
  build: images/nginx
  ports:
    - "80:80"
    - "9000:9000"
  links:
    - mysql:mysql
  volumes:
    - www:/var/www
    - sites:/etc/nginx/sites-enabled

mysql:
  image: tutum/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_PASS: password

